### ISSUE TITLE
Upload logo for Coasterpedia Github project

### ISSUE THREAD

**Issue by neoncitylights** [Coasterpedia/coasterpedia#1]
This should be uploaded to help make the Coasterpedia project look more official rather than have a boring, default and auto-generated image. :P How about this image I found? :D (great logo btw!) From what I found this seems to be the latest version:

http://coasterpedia.net/w/images/c/c0/Coasterpedia_logo.png

**Comment by lachlanshanks** [comment]
Thanks! I have gone for the circle on its own, it's better suited to a square profile picture.
